"""v2.0

Revision ID: 80101d94ad07
Revises: 8ca9d76b510d
Create Date: 2025-06-09 00:42:13.215338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80101d94ad07'
down_revision: Union[str, None] = '8ca9d76b510d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('operations', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('operations_barista_id_fkey'), 'operations', type_='foreignkey')
    op.create_foreign_key(None, 'operations', 'staff', ['staff_id'], ['id'])
    op.drop_column('operations', 'barista_id')
    op.drop_column('users', 'role')
    op.drop_table('barista')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('operations', sa.Column('barista_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.create_foreign_key(op.f('operations_barista_id_fkey'), 'operations', 'barista', ['barista_id'], ['id'])
    op.drop_column('operations', 'staff_id')
    op.create_table('barista',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('barista_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('barista_pkey'))
    )
    op.drop_table('staff')
    # ### end Alembic commands ###
